### ISSUE TITLE
偶尔运行报错

### ISSUE THREAD

**Issue by jun1362008** [HsuanXyz/ionic2-city-picker#4]
你好，我可以正常运行，但是有时候改变了子类后再改变父类有时候会报错。比如改变了市再改变省或者改变了区再改变省或市。
`Runtime Error
undefined is not an object (evaluating 'opt._dur')
Stack
update@http://192.168.0.13:8100/build/main.js:77317:33
refresh@http://192.168.0.13:8100/build/main.js:77375:24
forEach@[native code]
forEach@http://192.168.0.13:8100/build/main.js:6051:72
refresh@http://192.168.0.13:8100/build/main.js:77595:27
refresh@http://192.168.0.13:8100/build/main.js:94242:78
http://192.168.0.13:8100/build/main.js:132890:27
http://192.168.0.13:8100/build/main.js:4139:51
__tryOrUnsub@http://192.168.0.13:8100/build/main.js:29875:20
next@http://192.168.0.13:8100/build/main.js:29824:34
_next@http://192.168.0.13:8100/build/main.js:29766:30
next@http://192.168.0.13:8100/build/main.js:29730:23
next@http://192.168.0.13:8100/build/main.js:70717:29
emit@http://192.168.0.13:8100/build/main.js:4113:80
_colChange@http://192.168.0.13:8100/build/main.js:77604:30

callWithDebugContext@http://192.168.0.13:8100/build/main.js:13339:47
http://192.168.0.13:8100/build/main.js:4139:51
__tryOrUnsub@http://192.168.0.13:8100/build/main.js:29875:20
next@http://192.168.0.13:8100/build/main.js:29824:34
_next@http://192.168.0.13:8100/build/main.js:29766:30
next@http://192.168.0.13:8100/build/main.js:29730:23
next@http://192.168.0.13:8100/build/main.js:70717:29
emit@http://192.168.0.13:8100/build/main.js:4113:80
[native code]
onInvoke@http://192.168.0.13:8100/build/main.js:4424:43
run@http://192.168.0.13:8100/build/polyfills.ng.js:2:704
update@http://192.168.0.13:8100/build/main.js:77352:35
decelerate@http://192.168.0.13:8100/build/main.js:77206:24
[native code]`
`Uncaught TypeError: Cannot read property '_dur' of undefined
    at PickerColumnCmp.update (http://localhost:8100/build/main.js:77317:33)
    at PickerColumnCmp.refresh (http://localhost:8100/build/main.js:77375:18)
    at http://localhost:8100/build/main.js:77595:62
    at Array.forEach (native)
    at QueryList.forEach (http://localhost:8100/build/main.js:6051:65)
    at PickerCmp.refresh (http://localhost:8100/build/main.js:77595:20)
    at Picker.refresh (http://localhost:8100/build/main.js:94242:71)
    at picker.ionChange.subscribe (http://localhost:8100/build/main.js:132890:20)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8100/build/main.js:4139:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/main.js:29875:16)
    at SafeSubscriber.next (http://localhost:8100/build/main.js:29824:22)
    at Subscriber._next (http://localhost:8100/build/main.js:29766:26)
    at Subscriber.next (http://localhost:8100/build/main.js:29730:18)
    at EventEmitter.Subject.next (http://localhost:8100/build/main.js:70717:25)
    at EventEmitter.emit (http://localhost:8100/build/main.js:4113:76)`

**Comment by hsuanxyz** [comment]
我会尝试重现错误并解决，感谢你的issues

**Comment by YouSirY** [comment]
这个问题我也碰到了
